version: "3.9"

services:
  postgres:
    # Why Debezium's Postgres image?
    # - Ships with logical decoding plugins and sane defaults for CDC (e.g., wal_level=logical and `wal2json` output plugin).
    # - Simplifies Transaction Log Tailing demos: no extra Postgres tuning required.
    # - For production you can use the official postgres image, but you must configure
    #   logical decoding and replication settings yourself.
    image: debezium/postgres:14-alpine
    container_name: message-relay-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      # Why mount migrations here?
      # - Any *.sql in /docker-entrypoint-initdb.d is executed automatically
      #   ONLY on first database initialization (empty data dir/volume).
      # - This guarantees a ready-to-use schema for both patterns with zero manual steps.
      # - If you change migrations and want them to re-run, use `make reset` to recreate the volume.
      - ./db/migrations:/docker-entrypoint-initdb.d

      # Why mount seeds separately?
      # - Seeds are NOT executed automatically. We run them explicitly via `make seed`.
      # - This keeps demos deterministic, lets practitioners re-seed anytime,
      #   and avoids accidental side-effects on container restart.
      - ./db/seeds:/seeds
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 60s
      retries: 5

  kafka:
    # Why Bitnami's Kafka image?
    # - Easy single-node KRaft mode (no ZooKeeper) via environment variables.
    # - Great for local education labs: one container, quick startup, minimal config.
    image: bitnami/kafka:3.7
    container_name: message-relay-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    healthcheck:
      test: ["CMD-SHELL","/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 60s
      retries: 5

  polling-publisher-relay:
    build:
      context: ./polling_publisher
      dockerfile: ../Dockerfile
    container_name: polling-publisher-relay
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_DSN: "postgres://postgres:password@postgres:5432"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  transaction-log-tailing-relay:
    build:
      context: ./transaction_log_tailing
      dockerfile: ../Dockerfile
    container_name: transaction-log-tailing-relay
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_DSN: "postgres://postgres:password@postgres:5432"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      REPLICATION_SLOT_NAME: "outbox"  # Name of the logical replication slot. It created in `002` migration.

volumes:
  pgdata:
    driver: local
